# Introduction to Numpy

In [1]:
import numpy as np 

## Datatypes & Attributes

In [2]:
a1 = np.array([1e1000, 2, 3])

In [3]:
a1.dtype

dtype('float64')

In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

## Creating arrays

In [7]:
ones= np.ones(shape=(10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
zeros = np.zeros(shape=(2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
range_arr = np.arange(0, 12.25, 0.25)
range_arr

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,
        4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,
        6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,
        9.  ,  9.25,  9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  ,
       11.25, 11.5 , 11.75, 12.  ])

In [10]:
rand_arr = np.random.randint(0, 11, size=(2, 3))
rand_arr

array([[10,  3,  8],
       [10,  5,  7]])

## Random seeds

In [12]:
rng = np.random.default_rng(13245)
rand_arr4 = rng.integers(low=0, high=10, size=(5,3))
rand_arr4

array([[4, 3, 5],
       [3, 6, 1],
       [8, 6, 3],
       [2, 7, 3],
       [8, 3, 6]], dtype=int64)

In [13]:
rand_arr5 = rng.random(size=(5,3))
rand_arr5

array([[0.55406795, 0.10387903, 0.66610263],
       [0.5540228 , 0.11947387, 0.1918658 ],
       [0.94183941, 0.97738971, 0.55104394],
       [0.7248681 , 0.03136518, 0.90837705],
       [0.36462381, 0.99656724, 0.53668923]])

In [14]:
np.unique(rand_arr4)

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [15]:
a1

array([inf,  2.,  3.])

In [16]:
a1[0]

inf

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [18]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a3[0][0]

array([1, 2, 3])

In [20]:
a3[0][0][2]

3

In [21]:
a3[:2][:2][:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Manipulating arrays

In [23]:
a1 = np.array([1, 2, 3])
ones = np.ones(3)

In [24]:
a1 + ones

array([2., 3., 4.])

In [25]:
a1 * ones

array([1., 2., 3.])

In [26]:
np.dot(a1, ones)

6.0

In [29]:
np.multiply(a1, ones)

array([1., 2., 3.])

In [30]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [33]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [34]:
a2.shape

(2, 3)

In [37]:
a4 = a2.reshape((2,3,1))
a4

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [36]:
a3 * a4

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

### Aggregation

In [39]:
a1.sum()

6

In [40]:
a1.prod()

6

In [41]:
a1.cumsum()

array([1, 3, 6])

In [42]:
a1.cumprod()

array([1, 2, 6])

In [43]:
mass_arr = rng.integers(0, 100, 10000)

In [44]:
%timeit sum(mass_arr)
%timeit mass_arr.sum()

745 µs ± 85 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.48 µs ± 332 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [47]:
nut_sales = np.array([
                   [2, 7, 1], # Mon
                   [9, 4, 16], # Tues
                   [11, 14, 18], # Wed
                   [13, 13, 16], # Thurs
                   [15, 18, 9] # Fri
                   ]) 

nut_sales

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [50]:
prices = np.array([10, 8, 12])

In [51]:
nut_sales.shape, prices.shape

((5, 3), (3,))

In [53]:
daily_sales = np.dot(nut_sales, prices)
total_sales = daily_sales.sum()


In [54]:
daily_sales, total_sales

(array([ 88, 314, 438, 426, 402]), 1668)

In [1]:
# convert image into numpy array
from matplotlib.image import imread 

<img src="panda.png">

In [2]:
panda_pic = imread('panda.png')
panda_pic

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0